---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: SMI-S Provider를 설치하기 전에 Windows 호스트에서 지원되는 운영 체제를 실행 중인지 확인해야 합니다. 
---
= 지원되는 운영 체제 버전입니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
SMI-S Provider는 별도의 Windows 가상 머신(VM)에 설치하는 것을 권장합니다. 이 가상 머신은 안전하고 편리한 관리를 위해 동일한 도메인에 있을 수 있습니다.

SMI-S Provider를 설치하기 전에 Windows 호스트에서 지원되는 운영 체제를 실행 중인지 확인해야 합니다.

[cols="3*"]
|===
| 운영 체제 | 지원되는 버전 | 필요한 클라이언트 소프트웨어 


 a| 
Windows
 a| 
* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

 a| 
Microsoft Visual C++ 2010 런타임 라이브러리는 SMI-S 공급자 설치 중에 자동으로 설치됩니다. 런타임 라이브러리와 관련된 잠재적인 문제를 방지하려면 다음 위치에서 Microsoft Visual C++ 2010 재배포 가능 패키지(x86)를 설치해야 합니다. http://www.microsoft.com[]

|===


== 공급자 호스트 장비가 사양을 충족하는지 확인하십시오.

SMI-S Provider를 실행하려면 공급자 호스트 시스템이 다음 사양을 충족해야 합니다.

* 해당 공급자는 Hyper-V 노드에 직접 설치할 수 없습니다. 대신 Hyper-V 가상 머신에 설치할 수 있습니다.
* 공급자 호스트 시스템에서는 System Center Virtual Machine Manager(SCVMM)가 실행 중이면 안 됩니다.
* 공급자 호스트 컴퓨터는 메모리를 많이 사용하는 다른 프로그램을 실행하지 않아야 합니다.
* 공급자 호스트 시스템은 다른 공급업체의 SMI-S 공급자를 실행해서는 안 됩니다.

