---
permalink: reference-types-of-cim-users-and-associated-operations.html 
sidebar: sidebar 
keywords: smi-s provider, various types, control, access 
summary: SMI-S Provider를 사용할 때 CIM 서버에 대한 액세스를 제어하기 위해 사용자에게 할당할 수 있는 다양한 유형의 사용자가 있습니다. 
---
= CIM 사용자 유형 및 관련 작업
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SMI-S Provider를 사용할 때 CIM 서버에 대한 액세스를 제어하기 위해 사용자에게 할당할 수 있는 다양한 유형의 사용자가 있습니다.

이 릴리즈부터 도메인 사용자는 SMI-S Provider 사용자 데이터베이스 및 기타 구성 설정을 로컬 관리자 그룹의 도메인 사용자로 수정할 수 있습니다.

다음 표에는 CIM 서버에서 지원되는 사용자 및 각 유형에서 수행할 수 있는 작업이 나열되어 있습니다.

[cols="2*"]
|===
| 사용자 유형입니다 | 운영 


 a| 
Administrators 그룹의 도메인 관리자입니다
 a| 
'cimconfig' 및 'cimuser' 명령을 사용한 SMI-S Provider 구성 및 사용자 관리 예를 들면 다음과 같습니다.

* SMI-S Provider의 트러스트 저장소에 사용자를 추가하거나 제거합니다.
* 로그 수준 및 추적 구성을 활성화, 비활성화 또는 변경합니다.
* SMI-S Provider에서 인증 엔진을 설정하거나 해제합니다.


'mis' 및 'cimcli' 명령을 사용한 스토리지 관리 및 검증 예를 들면 다음과 같습니다.

* SMI-S Provider 저장소 또는 데이터베이스 또는 캐시에 스토리지 컨트롤러 또는 SVM을 추가 또는 제거합니다.
* SMI-S Provider 캐시에서 스토리지 컨트롤러 또는 SVM을 업데이트합니다.
* 스토리지 컨트롤러 또는 SVM 관리 확인


SCVMM GUI를 사용한 SCVMM 검색 작업



 a| 
로컬 관리자 그룹의 도메인 사용자입니다



 a| 
로컬 관리자 그룹의 로컬 사용자입니다



 a| 
기본 제공 도메인 관리자 사용자



 a| 
기본 제공 로컬 관리자 사용자



 a| 
Users 그룹의 도메인 사용자입니다
 a| 
SCVMM GUI를 사용한 SCVMM 검색 작업



 a| 
Users 그룹의 로컬 사용자입니다

|===
[NOTE]
====
Windows 호스트에 SMI-S Provider가 있고 "Administrator" 사용자 이름을 변경한 경우 시스템에서 로그아웃한 다음 다시 로그인해야 합니다. SMI-S Windows 서비스는 이 기간 동안 인증을 상속하므로 관리자가 로그아웃한 다음 다시 로그인할 때까지 자격 증명의 변경 내용을 인식하지 못합니다.

====