---
permalink: reference-possible-errors-when-loading-shared-libraries.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: NetApp SMI-S Provider에서 문제가 발생했습니다. 
---
= 공유 라이브러리를 로드하는 동안 오류가 발생할 수 있습니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
* 메시지 *
+
''공유 라이브러리 로드 중 오류: libssl.so 1.0.0: 공유 객체 파일을 열 수 없습니다: 해당 파일 또는 디렉토리가 없습니다.

+
'mis cimserver' 상태는 cimserver가 정상적으로 실행 중인 것으로 표시되지만 다른 모든 "/usr/NetApp/SMIS/Pegasus/bin/CIM" 명령은 다양한 오류 메시지를 표시합니다.

+
예를 들어, 'cimserver'를 실행할 때 'cimserver not running' 메시지가 표시되거나, '/usr/NetApp/SMIS/Pegasus/bin/cimcli:symbol lookup error:/usr/NetApp/SMIS/Pegasus/bin/cimcli:undefined intsymbol:_ZN7Pegasus16Stringsymbol.Todecime64c.tense64m_Conversecurs.cpu64m_tecurs.cdecime64m_Converse64m_tec 이러한 예는 모두 포함되어 있지는 않습니다.

* * 설명 *
+
LD_LIBRARY_PATH 환경이 설치 디렉토리로 설정되지 않은 경우 이 메시지(및 유사 메시지)가 발생한다.

* * 시정 조치 *
+
다음 명령 중 하나를 입력하여 'LD_LIBRARY_PATH' 환경 변수를 설치 디렉토리로 설정합니다.



'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/NetApp/SMIS/Pegasus/lib'

'setenv LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/NetApp/SMIS/Pegasus/lib'
