---
permalink: task-generate-a-self-signed-certificate-for-the-cim-server-windows.html 
sidebar: sidebar 
keywords: ssl authentication, enable, cim server, installation, self-signed certificate 
summary: 기본적으로 CIM 서버에 대해 SSL 인증이 활성화됩니다. SMI-S Provider를 설치하는 동안 CIM 서버에 대한 자체 서명된 인증서가 Pegasus 디렉토리에 설치됩니다. 자체 서명된 인증서를 생성하여 기본 인증서 대신 사용할 수 있습니다. 
---
= CIM 서버에 대해 자체 서명된 인증서를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
기본적으로 CIM 서버에 대해 SSL 인증이 활성화됩니다. SMI-S Provider 설치 중에 CIM 서버의 자체 서명된 인증서가 'Pegasus' 디렉토리에 설치됩니다. 자체 서명된 인증서를 생성하여 기본 인증서 대신 사용할 수 있습니다.

.시작하기 전에
* 관리자로 이미 로그인되어 있어야 합니다.
* SMI-S Provider를 이미 액세스한 상태여야 합니다.


.단계
. 를 다운로드합니다 `openssl.cnf` 다음 위치의 파일: link:http://web.mit.edu/crypto/openssl.cnf["http://web.mit.edu/crypto/openssl.cnf"^]
. 를 이동합니다 `openssl.cnf` bin 디렉토리에 파일 저장:
+
`*%PEGASUS_HOME%\bin\openssl.cnf*`

. 를 설정합니다 `OPENSSL_CONF` 의 위치에 대한 환경 변수입니다 `openssl.cnf` 파일:
+
`*C:\ >set OPENSSL_CONF=%PEGASUS_HOME%\bin\openssl.cnf*`

+
현재 명령 프롬프트 세션의 지속 시간에 대한 환경 변수만 설정합니다. 환경 변수를 영구적으로 설정하려는 경우 다음 옵션 중 하나를 사용할 수 있습니다.

+
** 속성 > 환경 변수 * 로 이동하고 * 시스템 * 에서 변수를 업데이트합니다.
** 명령 프롬프트를 사용하여 변수를 영구적으로 설정합니다.
+
`*setx OPENSSL_CONF “%PEGASUS_HOME%\bin\openssl.cnf*`.

+
이 변수는 새 명령 프롬프트 세션을 열 때 설정됩니다.



. 로 이동합니다 `%PEGASUS_HOME%\bin` 디렉터리:
+
`*C:\cd %pegasus_home%\bin*`

. 개인 키 생성:
+
'* openssl genrsa-out cimom.key 2048 *

. 인증서 요청 생성:
+
'* openssl req-new-key cimom.key-out cimom.csr *

. 메시지가 표시되면 인증서 요청에 대한 정보를 입력합니다.
. 자체 서명된 인증서 생성:
+
``openssl x509-in cimom.csr-out cimom.cert-req-signkey cimom.key -days 1095 *

+
인증서가 유효한 다른 일 수를 제공할 수 있습니다.

. cimom.key와 cimom.cert 파일을 pegasus 디렉토리(windows:'C:\Program Files (x86)\NetApp\SMIS\Pegasus')에 복사합니다.




== 결과

인증서 날짜 범위는 현재 날짜에 시작되고 지정된 일 수에 대해 실행됩니다.
