---
permalink: task-manage-cimom-configuration-settings.html 
sidebar: sidebar 
keywords: smi-s provider, to manage, cimom configuration, enable, disable, http, https, port numbers 
summary: SMI-S Provider를 사용하여 HTTP 및 HTTPS 연결 활성화 또는 비활성화, HTTP 및 HTTPS 포트 번호 변경 등의 CIMOM 구성을 관리할 수 있습니다. 기본적으로 HTTP 연결이 활성화되어 클라이언트가 SSL 암호화를 사용하지 않고 CIM 서버에 연결할 수 있습니다. 
---
= CIMOM 구성 설정을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SMI-S Provider를 사용하여 HTTP 및 HTTPS 연결 활성화 또는 비활성화, HTTP 및 HTTPS 포트 번호 변경 등의 CIMOM 구성을 관리할 수 있습니다. 기본적으로 HTTP 연결이 활성화되어 클라이언트가 SSL 암호화를 사용하지 않고 CIM 서버에 연결할 수 있습니다.

.시작하기 전에
* 이미 관리자로 로그인 자격 증명이 있어야 합니다.
* 호스트 시스템에 관리자로 이미 로그인되어 있어야 합니다.


환경에서 CIM 서버와 주고받는 암호화된 트래픽이 필요한 경우 먼저 HTTP 연결을 비활성화한 다음 CIM 서버에 대한 HTTPS 연결이 활성화되어 있는지 확인해야 합니다.

.단계
. NetApp SMI-S Provider에 액세스합니다.
. 다음 작업 중 하나를 수행합니다.
+
[cols="3*"]
|===
| 조치 | 명령 | 추가 정보 


 a| 
HTTP 연결을 활성화합니다
 a| 
(* cimconfig -s enableHttpConnection=true-p *)
 a| 
해당 없음



 a| 
HTTP 연결을 비활성화합니다
 a| 
'* cimconfig -s enableHttpConnection=false-p*'
 a| 
해당 없음



 a| 
HTTPS 연결을 활성화합니다
 a| 
'* cimconfig -s enableHttpsConnection=true-p *'
 a| 
해당 없음



 a| 
HTTPS 연결을 비활성화합니다
 a| 
'* cimconfig -s enableHttpsConnection=false-p *'
 a| 
해당 없음



 a| 
HTTP 포트 번호를 수정합니다
 a| 
'* cimconfig -s httpPort=_new_port_number_-p *'
 a| 
기본적으로 HTTP 포트 번호는 5988입니다. 예를 들어 5555로 변경하려면 다음 명령을 입력합니다.

'* cimconfig-s httpPort=5555-p *'



 a| 
HTTPS 포트 번호를 수정합니다
 a| 
'* cimconfig -s e포 포트=_new_port_number_-p*'
 a| 
기본적으로 HTTP 포트 번호는 5989입니다. 예를 들어 5556으로 변경하려면 다음 명령을 입력합니다.

'* cimconfig-s e포 포트 = 5556-p *'

|===
. CIM 서버를 다시 시작합니다.
+
'* SMIS cimserver restart*'


